### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by shreyasminocha** [comment]
Hey Shalok. Have a look at #125 for updates on Librefox's status.

**Comment by ShalokShalom** [comment]
Then just close this repo?? Archive it, so others dont run into this. This is why this function exists. ^-^

**Comment by shreyasminocha** [comment]
@ShalokShalom Honestly, if I had control over the repo I would've, but @intika is the only one with access to the settings. When they disappeared, we forked it off and started our own thing; this repo is dead because we haven't heard from @intika in several months.

Regardless, thanks for taking the time to create a PR!

**Comment by ShalokShalom** [comment]
Thanks a lot

**Pull request closed without merging**
